const teamsView=document.getElementById('teams-view');
const switchStyle=document.createElement('style');switchStyle.textContent='.team-switcher{display:flex;gap:6px;margin-top:18px;padding:4px;background:#e8f0e7;border-radius:9px;width:max-content}.team-switcher button{border:0;background:transparent;border-radius:6px;color:#6f8878;padding:10px 14px;font:10px "DM Mono";cursor:pointer}.team-switcher button.active{background:#fff;color:#719541;box-shadow:0 2px 7px #173d2410}';document.head.appendChild(switchStyle);
if(teamsView){
  const switcher=document.createElement('div');switcher.className='team-switcher';switcher.innerHTML='<button type="button" class="active">Home team</button><button type="button">Away team</button>';teamsView.querySelector('.app-heading')?.appendChild(switcher);
  const awayMatchInput=document.getElementById('match-away');
  if(awayMatchInput){const awayMatchSelect=document.createElement('select');awayMatchSelect.id='match-away';awayMatchSelect.required=true;awayMatchSelect.innerHTML='<option value="">Select away team</option>';awayMatchInput.replaceWith(awayMatchSelect);if(awayMatchInput.value)awayMatchSelect.insertAdjacentHTML('beforeend',`<option selected>${awayMatchInput.value}</option>`)}
  const form=document.createElement('form');form.id='away-team-form';form.className='app-card app-form';form.innerHTML='<h2>Away team</h2><label>Team name<input id="away-team-name" required placeholder="e.g. Riverpark FC"></label><label>Captain<select id="away-captain" required><option value="">Select captain</option></select></label><label>Players<textarea id="away-players" required placeholder="One player per line"></textarea></label><button type="submit">Save away team</button><div class="form-message" id="away-team-message"></div>';
  const card=document.createElement('section');card.className='app-card formation-card';card.id='away-formation-card';card.style.gridColumn='1 / -1';card.innerHTML='<h2>Away team lineup</h2><div class="formation-tools"><label>Format<select id="away-format"></select></label></div><div class="formation-layout pool-empty"><div class="player-pool" id="away-player-pool"><h3>Drag players</h3></div><div class="football-pitch" id="away-football-pitch"><div class="pitch-box top"></div><div class="pitch-box bottom"></div></div></div><p class="formation-note">Drag players anywhere on the pitch and choose their exact role.</p><div class="formation-actions"><button type="button" class="delete-team">Delete away team</button></div>';
  teamsView.querySelector('.app-grid').append(form,card);
  const homeForm=document.getElementById('team-form'),homeCard=document.getElementById('home-formation-card');
  function showTeam(which){const home=which==='home';homeForm.style.display=home?'grid':'none';homeCard.style.display=home?'block':'none';form.style.display=home?'none':'grid';card.style.display=home?'none':'block';switcher.querySelectorAll('button').forEach((button,index)=>button.classList.toggle('active',index===(home?0:1)))}
  switcher.querySelectorAll('button').forEach((button,index)=>button.addEventListener('click',()=>showTeam(index?'away':'home')));showTeam('home');
  const format=card.querySelector('#away-format'),pool=card.querySelector('#away-player-pool'),pitch=card.querySelector('#away-football-pitch'),players=document.getElementById('away-players'),captain=document.getElementById('away-captain'),savedAway=JSON.parse(localStorage.getItem('footlyMvp')||'{}').awayTeam||{},roles=['GK','LB','CB','RB','LWB','RWB','DMF','CMF','LMF','RMF','AMF','LWF','RWF','SS','CF'];
  for(let n=3;n<=11;n++){const o=document.createElement('option');o.value=`${n}-a-side`;o.textContent=`${n}-a-side`;format.append(o)}
  document.getElementById('away-team-name').value=savedAway.name||'';players.value=(savedAway.players||[]).join('\n');format.value=savedAway.format||'5-a-side';if(savedAway.name&&awayMatchInput){const select=document.getElementById('match-away');select.innerHTML=`<option selected>${savedAway.name}</option>`}
  const names=()=>players.value.split('\n').map(x=>x.trim()).filter(Boolean),point=i=>i===0?[88,50]:i===1?[18,50]:i===2?[48,50]:[76,18+((i-3)%4)*21],role=(x,y)=>y>.84?'GK':y>.68?(x<.3?'LB':x>.7?'RB':'DMF'):y>.48?(x<.3?'LMF':x>.7?'RMF':'CMF'):y>.27?(x<.3?'LWF':x>.7?'RWF':'AMF'):(x<.3?'LWF':x>.7?'RWF':y<.16?'CF':'SS');
  function render(){const list=names(),total=+format.value.split('-')[0];captain.innerHTML='<option value="">Select captain</option>'+list.map(x=>`<option>${x}</option>`).join('');captain.value=list.includes(savedAway.captain)?savedAway.captain:'';pool.hidden=list.length<=total;card.querySelector('.formation-layout').classList.toggle('pool-empty',list.length<=total);pitch.querySelectorAll('.pitch-player').forEach(x=>x.remove());list.slice(0,total).forEach((name,i)=>{const p=document.createElement('div');p.className='pitch-player';p.draggable=true;p.dataset.name=name;const xy=point(i);p.style.top=xy[0]+'%';p.style.left=xy[1]+'%';p.innerHTML=`<img class="player-image" src="player.png" alt=""><select>${roles.map(x=>`<option>${x}</option>`).join('')}</select><small>${name}</small>`;p.querySelector('select').value=i===0?'GK':i===1?'CF':i===2?'CMF':role(xy[1]/100,xy[0]/100);p.addEventListener('dragstart',e=>e.dataTransfer.setData('text/plain',name));pitch.append(p)});list.slice(total).forEach(name=>{const b=document.createElement('button');b.className='pool-player';b.draggable=true;b.textContent=name;b.addEventListener('dragstart',e=>e.dataTransfer.setData('text/plain',name));pool.append(b)})}
  pitch.addEventListener('dragover',e=>e.preventDefault());pitch.addEventListener('drop',e=>{e.preventDefault();const p=[...pitch.querySelectorAll('.pitch-player')].find(x=>x.dataset.name===e.dataTransfer.getData('text/plain'));if(!p)return;const r=pitch.getBoundingClientRect(),x=(e.clientX-r.left)/r.width,y=(e.clientY-r.top)/r.height;p.style.left=x*100+'%';p.style.top=y*100+'%';p.querySelector('select').value=role(x,y)});players.addEventListener('input',render);format.addEventListener('change',render);form.addEventListener('submit',e=>{const lineup=[...pitch.querySelectorAll('.pitch-player')].map(p=>p.querySelector('select').value);if(!captain.value||!lineup.includes('GK')||!lineup.some(x=>['DMF','CMF','AMF','LMF','RMF'].includes(x))||!lineup.some(x=>['CF','SS','LWF','RWF'].includes(x))){e.preventDefault();alert('Away team needs a captain, GK, midfielder, and attacker.');return}const state=JSON.parse(localStorage.getItem('footlyMvp')||'{}');const teamName=document.getElementById('away-team-name').value.trim();state.awayTeam={name:teamName,captain:captain.value,players:names(),format:format.value,lineup:[...pitch.querySelectorAll('.pitch-player')].map(p=>({name:p.dataset.name,x:parseFloat(p.style.left),y:parseFloat(p.style.top),position:p.querySelector('select').value}))};localStorage.setItem('footlyMvp',JSON.stringify(state));const awaySelect=document.getElementById('match-away');if(awaySelect)awaySelect.innerHTML=`<option selected>${teamName}</option>`;document.getElementById('away-team-message').textContent='Away team saved.'});card.querySelector('.delete-team').addEventListener('click',()=>{if(confirm('Delete away team?')){const state=JSON.parse(localStorage.getItem('footlyMvp')||'{}');state.awayTeam=null;localStorage.setItem('footlyMvp',JSON.stringify(state));document.getElementById('away-team-message').textContent='Away team deleted.';render()}});render();
}
