import { auth, db, firebaseConfigured, requireUser, collection, doc, addDoc, getDocs, deleteDoc, query, orderBy, serverTimestamp } from './firebase-client.js';
const form=document.getElementById('discussion-form'),text=document.getElementById('post-text'),feed=document.getElementById('discussion-feed'),message=document.getElementById('discussion-message'),submit=document.getElementById('post-submit');
const escape=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
let currentUser=null;
function formatDate(value){if(!value)return 'Just now';const date=value.toDate?value.toDate():new Date(value);return Number.isNaN(date.getTime())?'Just now':date.toLocaleString([], {dateStyle:'medium',timeStyle:'short'})}
async function loadPosts(){if(!currentUser){feed.innerHTML='<p class="community-empty">Sign in to join the community discussion.</p>';return}try{const snapshot=await getDocs(collection(db,'communityPosts'));if(snapshot.empty){feed.innerHTML='<p class="community-empty">No discussions yet. Start the first one.</p>';return}const posts=snapshot.docs.sort((a,b)=>(b.data().createdAt?.seconds||0)-(a.data().createdAt?.seconds||0));feed.innerHTML=posts.map(item=>{const post=item.data();return `<article class="discussion-post"><div class="post-head"><span class="post-author">${escape(post.authorName||'Footly user')}</span><span class="post-date">${escape(formatDate(post.createdAt))}</span></div><p class="post-text">${escape(post.text)}</p>${post.authorId===currentUser.uid?`<button class="post-delete" data-delete="${item.id}" type="button">Delete</button>`:''}</article>`}).join('')}catch(error){console.error(error);const detail=error.code==='permission-denied'?'Firestore access denied. Deploy firestore.rules and make sure you are signed in.':error.code==='failed-precondition'?'Firestore is not enabled for this Firebase project.':'Could not connect to Firestore.';feed.innerHTML=`<p class="community-empty">${detail}</p>`}}
form.addEventListener('submit',async event=>{event.preventDefault();const value=text.value.trim();if(!currentUser||!value)return;submit.disabled=true;message.textContent='Posting…';try{await addDoc(collection(db,'communityPosts'),{text:value,authorId:currentUser.uid,authorName:currentUser.displayName||currentUser.email?.split('@')[0]||'Footly user',createdAt:serverTimestamp()});text.value='';message.textContent='Posted';await loadPosts()}catch(error){console.error(error);message.textContent='Could not post your message.'}finally{submit.disabled=false}});
feed.addEventListener('click',async event=>{const button=event.target.closest('[data-delete]');if(!button||!currentUser||!confirm('Delete this discussion post?'))return;button.disabled=true;try{await deleteDoc(doc(collection(db,'communityPosts'),button.dataset.delete));await loadPosts()}catch(error){console.error(error);button.disabled=false}});
if(!firebaseConfigured){message.textContent='Firebase is not configured.';form.querySelectorAll('textarea,button').forEach(item=>item.disabled=true)}else requireUser(async user=>{if(!user){location.href='auth.html';return}currentUser=user;await loadPosts()});
