import {showAvatars} from './avatars.js';
import { playerStats } from './match-core.js';
import { latestMatch } from './match-data.js';
import { firebaseConfigured, requireUser, db, collection, getDocs, getDoc, teamDoc, query, where, orderBy } from './firebase-client.js';
const style=document.createElement('style');style.textContent='.match-map-grid{display:grid;grid-template-columns:1fr 1fr;gap:16px}.match-map{position:relative;min-height:560px;border:3px solid #d8f0cc;border-radius:10px;overflow:hidden;background:repeating-linear-gradient(0deg,#347d31 0,#347d31 70px,#3b8736 70px,#3b8736 140px)}.match-map:before{content:"";position:absolute;inset:50% 0 auto;height:2px;background:#e8f7df}.match-map:after{content:"";position:absolute;width:110px;height:110px;left:50%;top:50%;transform:translate(-50%,-50%);border:2px solid #e8f7df;border-radius:50%}.match-map-box{position:absolute;left:50%;transform:translateX(-50%);width:42%;height:18%;border:2px solid #e8f7df}.match-map-box.top{top:0;border-top:0}.match-map-box.bottom{bottom:0;border-bottom:0}.map-player{position:absolute;z-index:2;transform:translate(-50%,-50%);width:100px;text-align:center;color:#fff;font:10px "DM Sans"}.map-player img{display:block;width:38px;height:38px;object-fit:contain;margin:0 auto -1px}.map-player b{display:inline-block;background:#071c13dd;border-radius:5px;padding:4px 6px;white-space:nowrap}.map-player small{display:block;color:#d9efc9;font:9px "DM Mono";margin-top:3px}@media(max-width:700px){.match-map-grid{grid-template-columns:1fr}.match-map{min-height:480px}}';document.head.appendChild(style);
const escape=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const local=()=>{const state=JSON.parse(localStorage.getItem('footlyMvp')||'{}');return state.match||JSON.parse(localStorage.getItem('footlyMatch')||'null')};
async function getMatch(user){return user&&db?latestMatch(user.uid):local()}
const mapPoint=(index,total)=>{const columns=Math.min(4,total),rows=Math.ceil(total/columns);return [rows===1?50:10+Math.floor(index/columns)*80/(rows-1),100*(index%columns+1)/(columns+1)];};
function mapMarkup(players){return `<div class="match-map"><div class="match-map-box top"></div><div class="match-map-box bottom"></div>${players.map((item,index)=>{const player=typeof item==='object'?item:{name:item},xy=Number.isFinite(player.x)&&Number.isFinite(player.y)?[player.y,player.x]:mapPoint(index,players.length);return `<div class="map-player" style="top:${xy[0]}%;left:${xy[1]}%"><span class="community-avatar" data-avatar-user="${escape(player.uid||'')}"><img src="player.png" alt=""></span><b>${escape(player.name)}</b><small>${escape(player.position||'')}</small></div>`}).join('')}</div>`}
function render(match){const box=document.getElementById('section-content');if(!match){box.innerHTML='<p class="content-copy">No match is currently available.</p>';return}const section=document.body.dataset.section,events=match.events||[],players=[...(match.players?.home||[]),...(match.players?.away||[])];if(section==='summary')box.innerHTML=`<div class="content-card"><h2>${escape(match.home)} ${escape(match.homeScore??0)} — ${escape(match.awayScore??0)} ${escape(match.away)}</h2><p>${escape(match.competition||'Football match')} · ${escape(match.venue||'Venue not set')}</p><p>${events.length} live events recorded.</p></div>`;if(section==='commentary')box.innerHTML=`<div class="content-card"><h2>Live commentary</h2>${events.length?events.slice().reverse().map(item=>`<div class="event-row"><strong>${escape(item.player||'Match update')}</strong><span>${escape(item.minute||'LIVE')}' · ${escape(item.note||item.type||'Update')}</span></div>`).join(''):'<p class="content-copy">No events recorded yet.</p>'}</div>`;if(section==='lineups'){const home=match.players?.home||[],away=match.players?.away||[];box.innerHTML=`<div class="match-map-grid"><div class="content-card"><h2>${escape(match.home)}</h2>${mapMarkup(home)}</div><div class="content-card"><h2>${escape(match.away)}</h2>${mapMarkup(away)}</div></div>`}if(section==='stats')box.innerHTML=`<div class="content-card"><h2>Individual player stats</h2><div class="event-row"><strong>Player · team</strong><span>Goals · Assists · Events</span></div>${playerStats(match).map(player=>`<div class="event-row"><strong>${escape(player.name)} · ${escape(player.side)}</strong><span>${player.goals} · ${player.assists} · ${player.events}</span></div>`).join('')||'<p class="content-copy">No player stats yet. Add named player events in the scorekeeper.</p>'}</div>`}
const callback=async user=>{if(firebaseConfigured&&!user){location.replace('auth.html');return}try{render(await getMatch(user));showAvatars()}catch(error){document.getElementById('section-content').textContent='Could not load match. Reload to retry.';console.error(error)}};if(firebaseConfigured)requireUser(callback);else render(local());
