import { latestMatch } from './match-data.js';
import { escapeHtml } from './match-core.js';
import { auth, db, firebaseConfigured, requireUser, signOut, userDoc, getDoc, collection, getDocs, deleteDoc, query, where, limit } from './firebase-client.js';
const clearButton=document.body.dataset.portal==='profile'?Object.assign(document.createElement('button'),{id:'clear-matches',type:'button',textContent:'Delete all match records'}):null;if(clearButton){clearButton.className='profile-actions profile-danger';document.querySelector('.profile-actions')?.before(clearButton)}
let profileUser=null;
const state=()=>JSON.parse(localStorage.getItem('footlyMvp')||'{}');
const match=()=>{const data=state();return data.match||JSON.parse(localStorage.getItem('footlyMatch')||'null')};
document.querySelector('.portal-nav').innerHTML='<a href="app.html">Home</a><a href="add-match.html">Matches</a><a href="stats.html">Stats</a><a href="profile.html">Profile</a>';
if(firebaseConfigured&&!auth.currentUser){document.body.hidden=true;location.replace('auth.html')}
if(document.body.dataset.portal==='stats'&&auth?.currentUser){
  try{const current=await latestMatch(auth.currentUser.uid),data=state();data.match=current;data.events=current?.events||[];localStorage.setItem('footlyMvp',JSON.stringify(data));if(current)localStorage.setItem('footlyMatch',JSON.stringify(current));else localStorage.removeItem('footlyMatch')}
  catch(error){console.error(error);document.querySelector('.portal-copy').textContent='Could not refresh stats. Showing saved data.'}
}
if(document.body.dataset.portal==='stats'){
  const data=state(),m=match(),events=data.events||m?.events||[],goals=events.filter(item=>item.type==='goal'||item.icon==='⚽').length, assists=events.filter(item=>item.type==='assist').length;
  document.getElementById('matches').textContent=m?'1':'0';document.getElementById('goals').textContent=goals;document.getElementById('assists').textContent=assists;document.getElementById('team').textContent=data.team?.name||'No home team';document.getElementById('match-summary').textContent=m?`${m.home} ${m.homeScore??0} — ${m.awayScore??0} ${m.away}`:'No match played yet';document.getElementById('event-list').innerHTML=events.length?events.slice().reverse().map(item=>`<div><strong>${escapeHtml(item.player||'Match update')}</strong><small>${escapeHtml(item.type||item.note||'Live event')}</small></div>`).join(''):'<p class="muted">No player events yet.</p>';
}
if(document.body.dataset.portal==='profile'&&firebaseConfigured)requireUser(async user=>{if(!user){location.href='auth.html';return}profileUser=user;document.getElementById('profile-email').textContent=user.email||'';document.getElementById('profile-name').textContent=user.displayName||user.email?.split('@')[0]||'Organizer';try{const snap=await getDoc(userDoc(user.uid));if(snap.exists())document.getElementById('profile-name').textContent=snap.data().displayName||document.getElementById('profile-name').textContent}catch(error){console.error(error)}});else if(document.body.dataset.portal==='profile'){document.getElementById('profile-name').textContent=state().user||'Organizer'}
clearButton?.addEventListener('click',async()=>{if(!profileUser||!confirm('Delete every match and live event from your account? This cannot be undone.'))return;clearButton.disabled=true;clearButton.textContent='Deleting…';try{while(true){const matches=await getDocs(query(collection(db,'matches'),where('organizerId','==',profileUser.uid),limit(50)));if(matches.empty)break;for(const match of matches.docs){while(true){const events=await getDocs(query(collection(db,'matches',match.id,'events'),limit(50)));if(events.empty)break;await Promise.all(events.docs.map(event=>deleteDoc(event.ref)))}await deleteDoc(match.ref);if(match.data().schemaVersion===3){while(true){const roster=await getDocs(query(collection(db,'users',profileUser.uid,'matchRosters',match.id,'players'),limit(50)));if(roster.empty)break;await Promise.all(roster.docs.map(player=>deleteDoc(player.ref)))}}}}const data=state();data.match=null;data.events=[];localStorage.setItem('footlyMvp',JSON.stringify(data));localStorage.removeItem('footlyMatch');clearButton.textContent='Match history deleted';}catch(error){console.error(error);clearButton.disabled=false;clearButton.textContent='Could not delete records'}});
document.getElementById('portal-logout')?.addEventListener('click',()=>firebaseConfigured&&auth?signOut(auth):location.href='index.html');
