import { auth, db, firebaseConfigured, requireUser, teamDoc, getDoc, setDoc, serverTimestamp } from './firebase-client.js';

const side=document.body.dataset.teamSide==='away'?'away':'home';
const state=JSON.parse(localStorage.getItem('footlyMvp')||'{}');
const legacy=JSON.parse(localStorage.getItem('footlyTeams')||'{}');
let team=state[side+'Team']||(side==='home'?state.team:null)||(side==='home'?legacy.home:legacy.away)||null;
let signedInUser=null;
const $=id=>document.getElementById(id), form=document.querySelector('.builder-form'), nameField=$('team-name'), captain=$('captain'), players=$('players'), format=$('team-format'), pool=$('player-pool'), pitch=$('football-pitch'), message=$('builder-message');
const positions=['GK','LB','CB','RB','LWB','RWB','DMF','CMF','LMF','RMF','AMF','LWF','RWF','SS','CF'];
for(let n=3;n<=11;n++){const option=document.createElement('option');option.value=`${n}-a-side`;option.textContent=`${n}-a-side`;format.append(option)}
const names=()=>players.value.split('\n').map(item=>item.trim()).filter(Boolean);
const point=index=>index===0?[88,50]:index===1?[18,50]:index===2?[48,50]:[76-Math.floor((index-3)/4)*25,18+(index-3)%4*21];
const roleAt=(x,y)=>y>.84?'GK':y>.68?(x<.3?'LB':x>.7?'RB':'DMF'):y>.48?(x<.3?'LMF':x>.7?'RMF':'CMF'):y>.27?(x<.3?'LWF':x>.7?'RWF':'AMF'):(x<.3?'LWF':x>.7?'RWF':y<.16?'CF':'SS');
function fillFields(){nameField.value=team?.name||'';players.value=(team?.players||[]).join('\n');format.value=team?.format||'5-a-side'}
function render(){
  const list=names(),total=Number(format.value.split('-')[0]),savedLineup=Array.isArray(team?.lineup)?team.lineup:[];
  const currentCaptain=captain.value||team?.captain||'';captain.innerHTML='<option value="">Select captain</option>'+list.map(item=>`<option>${item}</option>`).join('');if(list.includes(currentCaptain))captain.value=currentCaptain;
  pool.hidden=list.length<=total;pool.parentElement.classList.toggle('pool-empty',list.length<=total);pool.innerHTML='<h3>Drag players</h3>';pitch.querySelectorAll('.pitch-player').forEach(item=>item.remove());
  list.forEach((name,index)=>{const savedPlayer=savedLineup.find(item=>typeof item==='object'?item.name===name:item===name);if(index>=total){const item=document.createElement('button');item.type='button';item.className='pool-player';item.draggable=true;item.textContent=name;item.addEventListener('dragstart',event=>event.dataTransfer.setData('text/plain',name));pool.append(item);return}const xy=savedPlayer&&Number.isFinite(savedPlayer.x)?[savedPlayer.y,savedPlayer.x]:point(index);const player=document.createElement('div');player.className='pitch-player';player.draggable=true;player.dataset.name=name;player.style.top=xy[0]+'%';player.style.left=xy[1]+'%';const role=savedPlayer?.position||roleAt(xy[1]/100,xy[0]/100);player.innerHTML=`<img class="player-image" src="player.png" alt=""><select aria-label="Position for ${name}">${positions.map(item=>`<option ${item===role?'selected':''}>${item}</option>`).join('')}</select><small>${name}</small>`;player.querySelector('select').addEventListener('mousedown',event=>event.stopPropagation());player.addEventListener('dragstart',event=>event.dataTransfer.setData('text/plain',name));pitch.append(player)});
}
pitch.addEventListener('dragover',event=>event.preventDefault());pitch.addEventListener('drop',event=>{event.preventDefault();const player=[...pitch.querySelectorAll('.pitch-player')].find(item=>item.dataset.name===event.dataTransfer.getData('text/plain'));if(!player)return;const rect=pitch.getBoundingClientRect(),x=Math.max(0,Math.min(1,(event.clientX-rect.left)/rect.width)),y=Math.max(0,Math.min(1,(event.clientY-rect.top)/rect.height));player.style.left=x*100+'%';player.style.top=y*100+'%';player.querySelector('select').value=roleAt(x,y)});
players.addEventListener('input',render);format.addEventListener('change',render);
function lineupData(){return [...pitch.querySelectorAll('.pitch-player')].map(player=>({name:player.dataset.name,x:parseFloat(player.style.left),y:parseFloat(player.style.top),position:player.querySelector('select').value}))}
function valid(lineup){return captain.value&&lineup.some(item=>item.position==='GK')&&lineup.some(item=>['DMF','CMF','AMF','LMF','RMF'].includes(item.position))&&lineup.some(item=>['CF','SS','LWF','RWF'].includes(item.position))}
async function persist(){const record={name:nameField.value.trim(),captain:captain.value,players:names(),format:format.value,lineup:lineupData()};team=record;state[side+'Team']=record;if(side==='home')state.team=record;localStorage.setItem('footlyMvp',JSON.stringify(state));const oldTeams=JSON.parse(localStorage.getItem('footlyTeams')||'{}');oldTeams[side]=record;localStorage.setItem('footlyTeams',JSON.stringify(oldTeams));if(signedInUser)await setDoc(teamDoc(signedInUser.uid),{[side+'Team']:record,ownerId:signedInUser.uid,updatedAt:serverTimestamp()},{merge:true})}
form.addEventListener('submit',async event=>{event.preventDefault();const lineup=lineupData();if(!captain.value){message.textContent='Select the captain from the players list.';return}if(!valid(lineup)){message.textContent='Add a GK, midfielder, and attacker to the lineup.';return}try{await persist();message.textContent=`${side==='home'?'Home':'Away'} team saved.`}catch(error){message.textContent='Could not save team. Check your Firebase connection.';console.error(error)}});
$('delete-team').addEventListener('click',async()=>{if(!team||!confirm(`Delete ${side} team?`))return;team=null;state[side+'Team']=null;if(side==='home')state.team=null;localStorage.setItem('footlyMvp',JSON.stringify(state));const oldTeams=JSON.parse(localStorage.getItem('footlyTeams')||'{}');delete oldTeams[side];localStorage.setItem('footlyTeams',JSON.stringify(oldTeams));if(signedInUser)await setDoc(teamDoc(signedInUser.uid),{[side+'Team']:null,ownerId:signedInUser.uid,updatedAt:serverTimestamp()},{merge:true});fillFields();render();message.textContent=`${side==='home'?'Home':'Away'} team deleted.`});
fillFields();render();
if(firebaseConfigured)requireUser(async user=>{if(!user){location.href='auth.html';return}signedInUser=user;try{const snap=await getDoc(teamDoc(user.uid));if(snap.exists()){const data=snap.data();team=data[side+'Team']||team;if(team){state[side+'Team']=team;if(side==='home')state.team=team;localStorage.setItem('footlyMvp',JSON.stringify(state));fillFields();render()}}}catch(error){console.error('Could not load team',error)}});
